### ISSUE TITLE
Sometimes fire time series data is 1 day in the future

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mv-aicc-fire-shim#12]
_From @cstephen on May 17, 2017 2:11_

For example, today is May 16th and it's showing data for May 17th. Sounds like an off-by-one error in the data gap filling code.

_Copied from original issue: ua-snap/mapventure-tools#16_

**Comment by cstephen** [comment]
So far I'm having trouble figuring out why this happened on May 16th. The code looks correct:

```javascript
dayOfYear <= moment().dayOfYear()
```
Where `dayOfYear` on the left is the day being considered for processing or filling, and `moment().dayOfYear()` should be the current day.

Is the AWS instance running this set to the Alaska time zone? That could very likely be the issue.

**Comment by BobTorgerson** [comment]
The problem turned out to be that the container running the code for graph data had a different time zone than the host it was running on. It was set to UTC, so I need to update the deployment configuration in OpenShift to add the environment variable of TZ=America/Anchorage through the web GUI.
